// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rprgyceyksrcsqrtrome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcmd5Y2V5a3NyY3NxcnRyb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzE5NjIsImV4cCI6MjA2NzUwNzk2Mn0.ModO05onhU4l4FyV1Wpr3oMYGZ-zB8FYqkLy2Ro-uUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});